### ISSUE TITLE
missing loops for callflow toggles, misc. destinations, set cid

### ISSUE THREAD

**Issue by thutex** [nathan242/freepbx-custom-tools#1]
Just found this and wondering if this project is still alive, because this is a feature that freepbx should have by its own but still doesnt.

would be nice if it could be completed

**Comment by nathan242** [comment]
Unfortunately I am not currently developing this as I no longer have access to a FreePBX system.
I wrote those scripts a few years ago to assist with administration of a FreePBX system and put them into a public repository in the hope it would be useful for others.
Feel free to make any updates and you can submit a pull request.

**Comment by thutex** [comment]
it actually is very useful, just not very complete.
i've modified it to work and be a bit more extensible, but the code is not quite as clean as it could/should be.
if i find the time and the skill to clean it up, i will send in a PR.
